domain: secureblue-staging.github.io
url: https://secureblue-staging.github.io
baseurl: /secureblue-staging.github.io/

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"

exclude: "README.md"